#trigger: none
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ci/cd.yml
      - iac

pool:
  #vmImage: ubuntu-22.04
  name: vmmgmtX

parameters:
  - name: environments
    type: object
    default:
      - dev
      - stg
      - prod

stages:
  # - stage: build
  #   displayName: Build
  #   jobs:
  #     - ${{ each environment in parameters.environments }}:
  #         - job: validate_${{ environment }}
  #           displayName: Validate (${{ environment }})
  #           steps:
  #             - task: AzureCLI@2
  #               displayName: Validate deployment
  #               inputs:
  #                 azureSubscription: sp-infra-${{ environment }}-01
  #                 scriptType: pscore
  #                 scriptPath: iac/deploy.ps1
  #                 arguments: ${{ environment }} validate
  #         - job: whatif_${{ environment }}
  #           displayName: What-if (${{ environment }})
  #           dependsOn: validate_${{ environment }}
  #           steps:
  #             - task: AzureCLI@2
  #               displayName: What-if deployment
  #               inputs:
  #                 azureSubscription: sp-infra-${{ environment }}-01
  #                 scriptType: pscore
  #                 scriptPath: iac/deploy.ps1
  #                 arguments: ${{ environment }} what-if

  - stage: release_${{ parameters.environments[0] }}
    displayName: Release (${{ parameters.environments[0] }})
    jobs:
      - deployment: create_${{ parameters.environments[0] }}
        displayName: Create (${{ parameters.environments[0] }})
        environment: ${{ parameters.environments[0] }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzureCLI@2
                  displayName: Create deployment
                  inputs:
                    azureSubscription: sp-avd-${{ parameters.environments[0] }}-01
                    scriptType: pscore
                    scriptPath: iac/deploy.ps1
                    arguments: ${{ parameters.environments[0] }} create
