parameters:
  - name: environments
    type: object

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: iac
        displayName: Validate infrastructure
        steps:
          - ${{ each environment in parameters.environments }}:
              - task: AzureCLI@2
                displayName: Validate ${{ environment }}
                inputs:
                  azureSubscription: lz-${{ environment }}
                  scriptType: pscore
                  scriptPath: iac/deploy.ps1
                  arguments: ${{ environment }}
  - ${{ each environment in parameters.environments }}:
      - stage: ${{ environment }}
        displayName: Release (${{ environment }})
        condition: or(and(succeeded(), eq('${{ environment }}', 'utv')), and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main')))
        jobs:
          - deployment: iac
            displayName: Deploy infrastructure
            environment: ${{ environment }}
            strategy:
              runOnce:
                deploy:
                  steps:
                    - checkout: self
                    - task: AzureCLI@2
                      displayName: Deploy ${{ environment }}
                      inputs:
                        azureSubscription: lz-${{ environment }}
                        scriptType: pscore
                        scriptPath: iac/deploy.ps1
                        arguments: ${{ environment }}
