trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  azureServiceConnection: 'NameXXX'
  location: 'swedencentral'
  templateFile: './iac/main.bicep'

stages:
- stage: Build
  jobs:
  - job: Build
    steps: 
    - task: AzureCLI@2  
      displayName: 'build bicep artifact' 
      inputs: 
        azureSubscription: $(azureServiceConnection) 
        scriptType: 'pscore'  
        scriptLocation: 'inlineScript'  
        inlineScript: 'az bicep build --file ./iac/main.bicep'  
- stage: deploy
  jobs:
  - deployment: biceptoAzure
    displayName: 'Deploy bicep to Azure'
    environment: 'AzureDeployment'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: 'deploy bicep template'
            inputs:
              azureSubscription: $(azureServiceConnection) 
              scriptType: 'pscore'
              scriptPath: SubDeployment.ps1
