trigger: none

stages:
  - stage: sqldb_1
    displayName: sqldb-elastic-job
    pool: 
      vmImage: ubuntu-latest
    variables:
      sqlServer: 'sql-system-dev-01.database.windows.net'
      sqlDatabase: 'sqldb-elastic-job'  
      rgName: 'rg-sql-system-dev-01'  
    jobs:
      - job: sql
        displayName: sql
        steps:
          - task: PowerShell@2
            displayName: 'install sql module'
            inputs:
              targetType: inline
              script: |
                Install-Module SQLServer -Force

          - task: AzureCLI@3
            displayName: allow ip
            inputs:
              azureSubscription: 'sp-sub-labb-01'
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                  $HostIp = (Invoke-RestMethod -Uri ‘http://ifconfig.io/ip').Trim()
                  az sql server firewall-rule create -g $(rgName) -s '$(sqlServer)'.Replace('.database.windows.net', '') -n pipeline --start-ip-address $HostIp --end-ip-address $HostIp
                
          - task: AzureCLI@3
            displayName: sqldb-elastic-job
            inputs:
              azureSubscription: 'id-abc-dev-01'
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                $accessToken = az account get-access-token --resource https://database.windows.net/ --query accessToken -o tsv

                $query = @"
                INSERT INTO dbo.Computer
                (
                  Motherboard,
                  CPUCores,
                  HasWifi,
                  HasLTE,
                  ReleaseDate,
                  Price,
                  VideoCard
                )
                VALUES
                (
                  'ASUS B650',
                  16,
                  1,
                  0,
                  '2026-07-11',
                  14999.9900,
                  'RTX 5090'
                );
                "@

                Invoke-Sqlcmd `
                -Query $query `
                -ServerInstance $(sqlServer) `
                -Database $(sqlDatabase) `
                -AccessToken $accessToken `
                -ConnectionTimeout 15 `
                -TrustServerCertificate

          - task: AzureCLI@3
            displayName: remove ip
            condition: always()
            inputs:
              azureSubscription: 'sp-sub-labb-01'
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                  $HostIp = (Invoke-RestMethod -Uri ‘http://ifconfig.io/ip').Trim()
                  az sql server firewall-rule delete -g $(rgName) -s '$(sqlServer)'.Replace('.database.windows.net', '') -n pipeline
  
  - stage: sqldb_2
    displayName: sqldb-elastic-pool
    pool: 
      vmImage: windows-latest
    variables:
      sqlServer: 'sql-system-dev-01.database.windows.net'
      sqlDatabase: 'sqldb-elastic-pool'  
      rgName: 'rg-sql-system-dev-01'  
    jobs:
      - job: sql
        displayName: sql
        steps:
          - task: PowerShell@2
            displayName: 'install sql module'
            inputs:
              targetType: inline
              script: |
                Install-Module SQLServer -Force

          - task: AzureCLI@3
            displayName: allow ip
            inputs:
              azureSubscription: 'sp-sub-labb-01'
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                  $HostIp = (Invoke-RestMethod -Uri ‘http://ifconfig.io/ip').Trim()
                  az sql server firewall-rule create -g $(rgName) -s '$(sqlServer)'.Replace('.database.windows.net', '') -n pipeline --start-ip-address $HostIp --end-ip-address $HostIp
                
          - task: AzureCLI@3
            displayName: sqldb-elastic-pool
            inputs:
              azureSubscription: 'sp-sub-labb-01'
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                $accessToken = az account get-access-token --resource https://database.windows.net/ --query accessToken -o tsv

                $query = @"
                INSERT INTO dbo.WeatherInfo
                (
                  City,
                  Temperature,
                  Description
                )
                VALUES
                (
                  'Gothenburg',
                  32,
                  'hot day'
                );
                "@

                Invoke-Sqlcmd `
                -Query $query `
                -ServerInstance $(sqlServer) `
                -Database $(sqlDatabase) `
                -AccessToken $accessToken `
                -ConnectionTimeout 15 `
                -TrustServerCertificate

          - task: AzureCLI@3
            displayName: remove ip
            condition: always()
            inputs:
              azureSubscription: 'sp-sub-labb-01'
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                  $HostIp = (Invoke-RestMethod -Uri ‘http://ifconfig.io/ip').Trim()
                  az sql server firewall-rule delete -g $(rgName) -s '$(sqlServer)'.Replace('.database.windows.net', '') -n pipeline
                

