trigger: none

pool:
  name: vmmgmtX
parameters:
  - name: environments
    type: object
    default:
      - prod

stages:
  - stage: build
    displayName: Build
    jobs:
      - ${{ each environment in parameters.environments }}:
          - job: whatif_${{ environment }}
            displayName: What-if (${{ environment }})
            steps:
              - task: AzureCLI@2
                displayName: What-if deployment
                inputs:
                  azureSubscription: sp-governance-01
                  scriptType: pscore
                  scriptPath: iac-ampl/deploy.ps1
                  arguments: ${{ environment }} what-if
