trigger: none

pool:
  name: vm-labb
  ##demands: Agent.Name -equals vmmgmtdev01

steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: sp-container-registry-acrdocker01
- task: Docker@2
  inputs:
    command: 'buildAndPush' # 'buildAndPush' | 'build' | 'push' | 'login' | 'logout' | 'start' | 'stop'. Required. Command. Default: buildAndPush.
    repository: nginx01
    Dockerfile: '$(Build.Repository.LocalPath)/docker-pipeline/Dockerfile'    
    tags: |
          1.002
          1.001

