trigger:
  branches:
    include:
      - main
  paths:
    include:
      - bicep
pool:
  vmImage: ubuntu-latest

variables:
  serviceprincipal: sp-subconnect-01

parameters:
  - name: environments
    type: object
    default:
      - prod

stages:
  - stage: release_${{ parameters.environments[0] }}
    displayName: Release (${{ parameters.environments[0] }})
    jobs:
      - deployment: create_${{ parameters.environments[0] }}
        displayName: Create (${{ parameters.environments[0] }})
        environment: ${{ parameters.environments[0] }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzureCLI@2
                  displayName: Create deployment
                  inputs:
                    azureSubscription: $(serviceprincipal)
                    scriptType: pscore
                    scriptPath: bicep/pipeline/deploy.ps1
                    arguments: ${{ parameters.environments[0] }} create