trigger:
  branches:
    include:
      - main
  paths:
    include:
      - iac
      #- ci/azure-pipelines.yml

schedules:
- cron: '0 21 * * *'
  displayName: "auto"
  always: true
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-24.04

variables:
  azureSubscription: sub-a3care-prod-01 

parameters:
  - name: environment
    type: string
    default: prod  

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: iac
        displayName: Validate infrastructure
        steps:
          - task: AzureCLI@2
            displayName: ${{ parameters.environment }}
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: pscore
              scriptPath: ./iac/deploy.ps1
              arguments: ${{ parameters.environment }} what-if

  - stage: ${{ parameters.environment }}
    displayName: Release (${{ parameters.environment }})
    jobs:
      - deployment: iac
        displayName: Deploy infrastructure
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzureCLI@2
                  displayName: ${{ parameters.environment }}
                  inputs:
                    azureSubscription: $(azureSubscription)
                    scriptType: pscore
                    scriptPath: iac/deploy.ps1
                    arguments: ${{ parameters.environment }} create
